### ISSUE TITLE
[Bug] SocketException: Connection failed (OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by juppiiiii** [FILENORI/filenori-client#6]
```shell
flutter: Upload error: SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = 127.0.0.1, port = 12345
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
socket_patch.dart:721
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:984:12)
socket_patch.dart:984
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1908:26)
socket_patch.dart:1908
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)
socket_patch.dart:21
#4      Socket._connect (dart:io-patch/socket_patch.dart:2134:22)
socket_patch.dart:2134
#5      Socket.connect (dart:io/socket.dart:809:21)
socket.dart:809
#6      NetworkService.uploadPiece (package:filenori_client/data/services/network_service.dart:15:35)
network_service.dart:15
#7      FileRepositoryImpl.uploadFilePieces (package:filenori_client/data/repositories/file_repository_impl.dart:25:28)
file_repository_impl.dart:25
<asynchronous suspension>
#8      UploadFileUseCase.call (package:filenori_client/domain/usecases/upload_file_usecase.dart:16:28)
upload_file_usecase.dart:16
<asynchronous suspension>
#9      UploadNotifier.uploadFile (package:filenori_client/application/riverpod/upload_notifier.dart:48:26)
upload_notifier.dart:48
<asynchronous suspension>
#10     FileViewModel.uploadFile (package:filenori_client/presentation/viewmodels/file_viewmodel.dart:38:5)
file_viewmodel.dart:38
<asynchronous suspension>```

**Comment by juppiiiii** [comment]
- https://stackoverflow.com/questions/65458903/socketexception-connection-failed-os-error-operation-not-permitted-errno-1
- https://pogon.tistory.com/entry/Flutter-macOS-Connection-failed-OS-Error-Operation-not-permitted-errno-1#google_vignette
